[tool.black]
experimental_string_processing = true
line-length = 120
target-version = ['py310']

[tool.coverage.run]
omit = ["*/tests/*"]
source = ["."]

[tool.coverage.report]
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "@(abc.)?abstractmethod",
    "@overload",
]

[tool.isort]
line_length = 120
py_version = 310

[tool.mypy]
ignore_missing_imports = true
python_version = "3.10"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
pythonpath = ["."]
testpaths = ["tests"]

[tool.flake8]
exclude = "__init__.py"
max-line-length = 120
extend-ignore = ["E203"]
